/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedModelosRouteImport } from './routes/_authed.modelos'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as AuthedAgendaRouteImport } from './routes/_authed.agenda'
import { Route as AuthedProcessoAttendanceIdRouteImport } from './routes/_authed.processo.$attendanceId'
import { Route as AuthedAtendimentoNovoRouteImport } from './routes/_authed.atendimento.novo'
import { Route as AuthedAtendimentoIdRouteImport } from './routes/_authed.atendimento.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedModelosRoute = AuthedModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAgendaRoute = AuthedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProcessoAttendanceIdRoute =
  AuthedProcessoAttendanceIdRouteImport.update({
    id: '/processo/$attendanceId',
    path: '/processo/$attendanceId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAtendimentoNovoRoute = AuthedAtendimentoNovoRouteImport.update({
  id: '/atendimento/novo',
  path: '/atendimento/novo',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAtendimentoIdRoute = AuthedAtendimentoIdRouteImport.update({
  id: '/atendimento/$id',
  path: '/atendimento/$id',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthedAgendaRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/modelos': typeof AuthedModelosRoute
  '/atendimento/$id': typeof AuthedAtendimentoIdRoute
  '/atendimento/novo': typeof AuthedAtendimentoNovoRoute
  '/processo/$attendanceId': typeof AuthedProcessoAttendanceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthedAgendaRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/modelos': typeof AuthedModelosRoute
  '/atendimento/$id': typeof AuthedAtendimentoIdRoute
  '/atendimento/novo': typeof AuthedAtendimentoNovoRoute
  '/processo/$attendanceId': typeof AuthedProcessoAttendanceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authed/agenda': typeof AuthedAgendaRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/modelos': typeof AuthedModelosRoute
  '/_authed/atendimento/$id': typeof AuthedAtendimentoIdRoute
  '/_authed/atendimento/novo': typeof AuthedAtendimentoNovoRoute
  '/_authed/processo/$attendanceId': typeof AuthedProcessoAttendanceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenda'
    | '/dashboard'
    | '/modelos'
    | '/atendimento/$id'
    | '/atendimento/novo'
    | '/processo/$attendanceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agenda'
    | '/dashboard'
    | '/modelos'
    | '/atendimento/$id'
    | '/atendimento/novo'
    | '/processo/$attendanceId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/auth'
    | '/_authed/agenda'
    | '/_authed/dashboard'
    | '/_authed/modelos'
    | '/_authed/atendimento/$id'
    | '/_authed/atendimento/novo'
    | '/_authed/processo/$attendanceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/modelos': {
      id: '/_authed/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof AuthedModelosRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/agenda': {
      id: '/_authed/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthedAgendaRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/processo/$attendanceId': {
      id: '/_authed/processo/$attendanceId'
      path: '/processo/$attendanceId'
      fullPath: '/processo/$attendanceId'
      preLoaderRoute: typeof AuthedProcessoAttendanceIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/atendimento/novo': {
      id: '/_authed/atendimento/novo'
      path: '/atendimento/novo'
      fullPath: '/atendimento/novo'
      preLoaderRoute: typeof AuthedAtendimentoNovoRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/atendimento/$id': {
      id: '/_authed/atendimento/$id'
      path: '/atendimento/$id'
      fullPath: '/atendimento/$id'
      preLoaderRoute: typeof AuthedAtendimentoIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAgendaRoute: typeof AuthedAgendaRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedModelosRoute: typeof AuthedModelosRoute
  AuthedAtendimentoIdRoute: typeof AuthedAtendimentoIdRoute
  AuthedAtendimentoNovoRoute: typeof AuthedAtendimentoNovoRoute
  AuthedProcessoAttendanceIdRoute: typeof AuthedProcessoAttendanceIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAgendaRoute: AuthedAgendaRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedModelosRoute: AuthedModelosRoute,
  AuthedAtendimentoIdRoute: AuthedAtendimentoIdRoute,
  AuthedAtendimentoNovoRoute: AuthedAtendimentoNovoRoute,
  AuthedProcessoAttendanceIdRoute: AuthedProcessoAttendanceIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
